name: Update OpenMS dates

# Trigger this action manually
on:
  workflow_dispatch:

jobs:
  update_dates:
    runs-on: macos-latest
    steps:
      # Checkout the OpenMS/OpenMS repository
      - name: Checkout OpenMS/OpenMS
        uses: actions/checkout@v2
        with:
          repository: OpenMS/OpenMS

      # Update year numbers in files
      - name: Update year numbers
        run: |
          cd OpenMS
          find . -type f ! -path "./.git/*" -exec grep -q "Freie Universitaet Berlin 2002-20" {} \; -exec sed -i '' -e 's/and Freie Universitaet Berlin 2002-2022/and Freie Universitaet Berlin 2002-2023/g' {} \;

      # Check for changes
      - name: Check for changed files
        id: changed-files
        run: |
          cd OpenMS
          if git diff --exit-code; then
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "changes_exist=true" >> $GITHUB_ENV
          fi

      # Create pull request
      - name: Create pull request
        if: env.changes_exist == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update year numbers in files
          title: Update year numbers in files
          branch: update-year-numbers
          base: main
